### ISSUE TITLE
ImageOptim?

### ISSUE THREAD

**Issue by Victa** [nomadesign/ftw-retreat#22]
I don't know how the website is build when we merge to `master` but I was wondering if we can add some sort of images optimization task?  (perhaps there is already one!)

**Comment by lesliepassante** [comment]
@Victa I turned on `lossless compression` in netlify. Let me know it it looks better.

**Comment by Victa** [comment]
I guess :)

I was doing some random speed test such as https://tools.pingdom.com/#!/d4TjNm/http://forthewomenretreat.com and realized I forgot to drop the images in https://imageoptim.com/mac

Thanks!
