### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by Victa** [nomadesign/ftw-retreat#35]
- [x] @Victa to design the page
- [x] @kuanluo to work on the copy
- [x] @Victa to implement the page

**Comment by Victa** [comment]
I designed the page. We need to do a pass on the copy before being implemented cc @kuanluo 

![registration](https://user-images.githubusercontent.com/594365/42063576-59cd0d84-7b00-11e8-86cd-6890ff4660fa.png)

**Comment by kuanluo** [comment]
Copy: https://docs.google.com/document/d/1DdhvXqK5ANWFzL-whya4uRf4O3g-nHMTyBAtWadVDW8/edit#

Though I like the idea of having the Reserve Your Spot CTA at the bottom of the page, the photo grid seems a little out of place. If there is still a button to book on the top right of the page, then we can perhaps skip that section?

**Comment by Victa** [comment]
Cool. Looks good for you @kuanluo ?

![faq](https://user-images.githubusercontent.com/594365/42549455-824ce148-8489-11e8-965f-c23454c4ee8b.jpg)

**Comment by Victa** [comment]
done!
