### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by Victa** [nomadesign/ftw-retreat#36]
We need to update the home page with more info about the retreat.

- show more important info at a glance
- present the house/region
- add buttons/links to FAQ + Registration

---------

- [x] @Victa to design the page
- [x] @kuanluo to work on the copy
- [x] @Victa to implement the page

**Comment by kuanluo** [comment]
### Design feedback

- Love the 3 call-outs above the first body paragraph!
- To make the page feel more concise, what do you think about combining the photo grid (the last section) and the section of Mont Tremblant, Québec? The copy about the house can be directly after the photo collage? 

### Updated copy
https://docs.google.com/document/d/1DdhvXqK5ANWFzL-whya4uRf4O3g-nHMTyBAtWadVDW8/edit#

**Comment by kuanluo** [comment]
YES! Love it. ❤️

**Comment by Victa** [comment]
Homepage implemented! Will close once it's merged
