### ISSUE TITLE
Implement Evenbrite

### ISSUE THREAD

**Issue by Victa** [nomadesign/ftw-retreat#38]
@lesliepassante @kuanluo 

not 100% sure what are the next steps for the both of you on Evenbrite. Feel free to edit my comment.

---------------

- [x] @kuanluo finalize pricing/content on Eventbrite
- [x] @lesliepassante plug Eventbrite to the website

**Comment by kuanluo** [comment]
I copied the content to Eventbrite. 

@lesliepassante Can you take a pass at the copy and comment away: https://docs.google.com/document/d/1DdhvXqK5ANWFzL-whya4uRf4O3g-nHMTyBAtWadVDW8/edit#?

**Comment by Victa** [comment]
done!
