### ISSUE TITLE
Add a banner on top of the website

### ISSUE THREAD

**Issue by kuanluo** [nomadesign/ftw-retreat#48]
Example: http://www.forevermarvel.com/

Copy: Registration for Oct 4-8 FTWRetreat in Québec is open. Click to reserve your spot. 
Link to booking, obvs. :)

**Comment by Victa** [comment]
Done and merged

We also added "blog" to the header and removed the cta to buy a ticket (it was competing with the banner)

<img width="1291" alt="screen shot 2018-08-05 at 8 36 35 pm" src="https://user-images.githubusercontent.com/594365/43688753-41ee0670-98ef-11e8-9249-4bff99dbfb26.png">
