### ISSUE TITLE
Add this to FAQ

### ISSUE THREAD

**Issue by kuanluo** [nomadesign/ftw-retreat#69]
**I'd love to have my company pay for my trip. How can I do it?**  

Here is the list of what your company will get out of sending you to an FTW Retreat. 
- You are a happier employee from being re-energized & inspired in nature and in the group.
- Your team will be more productive from discussing issues that your team faces with other experienced women leaders in tech. 
- Your company will be on the radar for the group of women who might be looking for their next role.

**Comment by Victa** [comment]
I am also removing these two -> 
<img width="892" alt="cleanshot 2018-10-13 at 15 36 11 2x" src="https://user-images.githubusercontent.com/594365/46910209-b85dc180-cefd-11e8-80b8-1ac559c9d639.png">

**Comment by kuanluo** [comment]
Perfect!
