### ISSUE TITLE
Update Testimonials

### ISSUE THREAD

**Issue by Victa** [nomadesign/ftw-retreat#72]
I think we need to update this section with people from the official first retreat. Would be cool to have profile pictures too :)

<img width="1023" alt="cleanshot 2018-10-13 at 15 25 05 2x" src="https://user-images.githubusercontent.com/594365/46910108-2bfecf00-cefc-11e8-8aec-2ab2951806ca.png">

Assigning to @kuanluo

**Comment by kuanluo** [comment]
It's not a retreat, it's an experience. Kuan took care of every little detail. Between the incredible house, the delicious food, and the amazing women, this is the perfect way to unplug and find your people.
- Saron Yitbarek, Developer, Podcaster, Founder of CodeNewbie

One of the most fulfilling weekends I've had in a long time -- both professionally and personally.
- Bersabel Tadasse, Director of Product, Mapbox

FTW Retreat was the perfect time and space to be creative (I shipped the first draft of my book!), to revel in some stillness in nature, and to learn from other boss women.
- Lara Hogan, Engineering leadership coach and consultant. 

Thanks for crafting a perfect weekend of relaxation, great food and meaningful conversation - I left feeling incredibly recharged and inspired. 
- Amy Pan, Product management consultant

Folder of the headshots: https://drive.google.com/drive/folders/1OdPsNgDMEuMb2JRjncHAfkLopU0E9DPm?usp=sharing

**Comment by Victa** [comment]
![sketch 2018-10-19 at 17 08 16 2x](https://user-images.githubusercontent.com/594365/47247541-9498f080-d3c1-11e8-9aa1-9fd8fc4cc5dc.png)
