### ISSUE TITLE
Winter 2019 retreat website push 2/2 - Mobile

### ISSUE THREAD

**Issue by kuanluo** [nomadesign/ftw-retreat#79]
A few mobile issues: 
- [x] Testimonial is broken
- [x] Past Retreat and the arrow in the nav aren't lined up vertically. 
- [x] `A 5-day intimate...` headline font-size is too big. I would love for the sign-up to show above the scroll on Pixel-size devices.
- [x] Background color doesn't extend all the way to the right for the House section. 
- [x] Footer contact email font-size should be the same as privacy policy and code of conduct?

**Comment by Victa** [comment]
- [ ] Fix single house image on mobile (right now it's Quebec)
